language: go
go: "1.15"
os: linux

services:
  postgresql

before_script:
  - psql -c 'create database postgres_test;' -U postgres
  - psql -c "alter user postgres with password '1234';" -U postgres

jobs:
  include:
    - stage: test
      script:
        - go test ./... -coverprofile cover.out # unit tests
        - go test -tags=e2e ./... # e2e tests